### PR TITLE
this shoudl fix #30

### LINKED ISSUE #30: package.order
When trying to open the library in OpenModelica it complains about a broken `package.order`.

### PR DESCRIPTION
**Pull request by thorade**

### CODE REVIEW

**Comment by jowr** [comment]
Thanks for the pull request. What is going on? Missing models that appear in the `package.order`?

**Comment by thorade** [comment]
Looks like it. Maybe someone forgot to press the save button or forgot to upload the models also?
They are listed in the package.order, but they are not present.

**Comment by jowr** [comment]
That sounds like @adesideri should chime in here and either merge the pull request or upload the models. Thanks again for spotting this flaw.

**Comment by thorade** [comment]
OpenModelica spotted it. It is quite strict, that helps a lot.

**Pull request merged**
